"""add planning models

Revision ID: 923f44cd68de
Revises: 0002_create_athletes_table
Create Date: 2026-03-15 18:10:27.992634

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '923f44cd68de'
down_revision = '0002_create_athletes_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_athlete_id'), 'goals', ['athlete_id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_athlete_id'), 'training_plans', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_plans_goal_id'), 'training_plans', ['goal_id'], unique=False)
    op.create_table('training_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_plan_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('day_date', sa.Date(), nullable=False),
    sa.Column('day_notes', sa.Text(), nullable=True),
    sa.Column('day_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['training_plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_plan_id', 'day_date', name='uq_training_days_plan_date')
    )
    op.create_index(op.f('ix_training_days_athlete_id'), 'training_days', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_training_days_training_plan_id'), 'training_days', ['training_plan_id'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_day_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('discipline_variant', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description_text', sa.Text(), nullable=True),
    sa.Column('session_type', sa.String(length=100), nullable=True),
    sa.Column('session_order', sa.Integer(), nullable=False),
    sa.Column('planned_start_time', sa.Time(), nullable=True),
    sa.Column('expected_duration_min', sa.Integer(), nullable=True),
    sa.Column('expected_distance_km', sa.Float(), nullable=True),
    sa.Column('expected_elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('target_hr_zone', sa.String(length=50), nullable=True),
    sa.Column('target_power_zone', sa.String(length=50), nullable=True),
    sa.Column('target_notes', sa.Text(), nullable=True),
    sa.Column('is_key_session', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['training_day_id'], ['training_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_sessions_athlete_id'), 'planned_sessions', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_planned_sessions_training_day_id'), 'planned_sessions', ['training_day_id'], unique=False)
    op.create_index('ix_planned_sessions_training_day_order', 'planned_sessions', ['training_day_id', 'session_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planned_sessions_training_day_order', table_name='planned_sessions')
    op.drop_index(op.f('ix_planned_sessions_training_day_id'), table_name='planned_sessions')
    op.drop_index(op.f('ix_planned_sessions_athlete_id'), table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_training_days_training_plan_id'), table_name='training_days')
    op.drop_index(op.f('ix_training_days_athlete_id'), table_name='training_days')
    op.drop_table('training_days')
    op.drop_index(op.f('ix_training_plans_goal_id'), table_name='training_plans')
    op.drop_index(op.f('ix_training_plans_athlete_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_goals_athlete_id'), table_name='goals')
    op.drop_table('goals')
    # ### end Alembic commands ###
