"""add garmin activities

Revision ID: 9c4b2dd09d25
Revises: b1e27222b3e8
Create Date: 2026-03-15 20:37:32.677635

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '9c4b2dd09d25'
down_revision = 'b1e27222b3e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garmin_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=True),
    sa.Column('sport_type', sa.String(length=100), nullable=True),
    sa.Column('discipline_variant', sa.String(length=100), nullable=True),
    sa.Column('is_multisport', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('moving_duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('avg_power', sa.Integer(), nullable=True),
    sa.Column('max_power', sa.Integer(), nullable=True),
    sa.Column('normalized_power', sa.Integer(), nullable=True),
    sa.Column('avg_speed_mps', sa.Float(), nullable=True),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('avg_pace_sec_km', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('max_cadence', sa.Float(), nullable=True),
    sa.Column('training_effect_aerobic', sa.Float(), nullable=True),
    sa.Column('training_effect_anaerobic', sa.Float(), nullable=True),
    sa.Column('training_load', sa.Float(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('avg_temperature_c', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('raw_summary_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garmin_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garmin_activities_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index('ix_garmin_activities_athlete_start_time', ['athlete_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_garmin_activities_garmin_activity_id'), ['garmin_activity_id'], unique=True)

    op.create_table('garmin_activity_laps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('garmin_activity_id_fk', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_type', sa.String(length=50), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('moving_duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('avg_power', sa.Integer(), nullable=True),
    sa.Column('max_power', sa.Integer(), nullable=True),
    sa.Column('avg_speed_mps', sa.Float(), nullable=True),
    sa.Column('avg_pace_sec_km', sa.Float(), nullable=True),
    sa.Column('avg_cadence', sa.Float(), nullable=True),
    sa.Column('max_cadence', sa.Float(), nullable=True),
    sa.Column('stroke_count', sa.Integer(), nullable=True),
    sa.Column('swolf', sa.Integer(), nullable=True),
    sa.Column('raw_lap_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['garmin_activity_id_fk'], ['garmin_activities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('garmin_activity_id_fk', 'lap_number', name='uq_garmin_activity_lap_number')
    )
    with op.batch_alter_table('garmin_activity_laps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garmin_activity_laps_garmin_activity_id_fk'), ['garmin_activity_id_fk'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garmin_activity_laps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garmin_activity_laps_garmin_activity_id_fk'))

    op.drop_table('garmin_activity_laps')
    with op.batch_alter_table('garmin_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garmin_activities_garmin_activity_id'))
        batch_op.drop_index('ix_garmin_activities_athlete_start_time')
        batch_op.drop_index(batch_op.f('ix_garmin_activities_athlete_id'))

    op.drop_table('garmin_activities')
    # ### end Alembic commands ###
