"""add planned session steps

Revision ID: c6428e4dd784
Revises: 923f44cd68de
Create Date: 2026-03-15 19:57:03.552775

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'c6428e4dd784'
down_revision = '923f44cd68de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planned_session_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('planned_session_id', sa.Integer(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('repeat_count', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('target_hr_min', sa.Integer(), nullable=True),
    sa.Column('target_hr_max', sa.Integer(), nullable=True),
    sa.Column('target_power_min', sa.Integer(), nullable=True),
    sa.Column('target_power_max', sa.Integer(), nullable=True),
    sa.Column('target_pace_min_sec_km', sa.Integer(), nullable=True),
    sa.Column('target_pace_max_sec_km', sa.Integer(), nullable=True),
    sa.Column('target_cadence_min', sa.Integer(), nullable=True),
    sa.Column('target_cadence_max', sa.Integer(), nullable=True),
    sa.Column('target_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planned_session_steps_planned_session_id'), 'planned_session_steps', ['planned_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_planned_session_steps_planned_session_id'), table_name='planned_session_steps')
    op.drop_table('planned_session_steps')
    # ### end Alembic commands ###
